### ISSUE TITLE
Music pause

### ISSUE THREAD

**Issue by SzpiegDonPedro** [GCWizard/GCWizard#2008] opened 2024-11-17 17:38 UTC
I thought someone had already had this error, but it didn't - when I turn on the application, the music I'm playing it pauses by itself, although no tool plays anything. This is probably a Bug of app.

**Comment by S-Man42** [comment] 2024-11-17 17:59
On iOS the music player never worked. We always. had issues with the used library here...

I propose to close this issue because the problem is tackled by #985

**Closed** 2024-11-17 19:34 UTC
